# Generated by Django 5.0.1 on 2024-06-27 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_purchasetransaction_remove_usercryptocurrency_crypto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.purchasetransaction')),
            ],
        ),
    ]
