# Generated by Django 4.2 on 2024-07-06 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0014_carddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasetransaction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='crypto_amount',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
